version: '2'

services:

   ubooquity:
    restart: always
    image: zerpex/ubooquity-docker
    container_name: ubooquity
    volumes:
      - ./files/conf:/config
      - /library:/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Paris
    ports:
      - 2202:2202
      - 2502:2502

   watchtower:
    restart: always
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - ./files/watchtower_config.json:/config.json
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Paris

volumes:
  files:
    driver: local
