ubooquity:
  restart: always
  build: .
  container_name: ubooquity2
  volumes:
    - ./files/conf:/ubooquity-conf
    - /datastore/media/library:/opt/data
  environment:
    - TZ=Europe/Paris
  ports:
    - 55603:2202
    - 55604:2502
