ubooquity:
  restart: always
  image: zerpex/ubooquity-docker
  container_name: ubooquity2
  volumes:
    - ./files/conf:/opt/ubooquity-conf
    - /library:/opt/data
    - /etc/localtime:/etc/localtime:ro
  environment:
    - TZ=Europe/Paris
  ports:
    - 2202:2202
    - 2502:2502
